spring:
  application:
    name: weather-svc
  datasource:
    url: jdbc:mysql://localhost:3306/weather_svc
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baselineOnMigrate: true
    validateOnMigrate: true
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: update

  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: "*"
server:
  port: 8090

openWeather-map:
  api:
    url: http://localhost:8080/api/v1/forecast/cityName