CREATE TABLE IF NOT EXISTS `consumer_audit`(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    event_type VARCHAR(50) NOT NULL,
    state VARCHAR(20) NOT NULL,
    content LONGTEXT NOT NULL
    );